### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by uniqname** [zacanger/koa-lowercase#1]
I'm getting "Unexpected token '('" Error:

```
const lowercase = async (ctx, next) => {
                        ^
```

Node v8.0.0

**Comment by zautumnz** [comment]
Can you double check that you're actually on Node 8? This works perfectly fine for me.

```
> process.version
'v8.0.0'
> require('koa-lowercase').default()
Promise {
//
```

**Comment by zautumnz** [comment]
@uniqname can I consider this resolved?

**Comment by zautumnz** [comment]
I'm going to close this as it seems to be fine in Node 8.
